### ISSUE TITLE
Vim statusline never changes.

### ISSUE THREAD

**Issue by sarbazx** [astrails/dotvim#59] opened 2016-04-27 08:22 UTC
Despite changing airline themes changes not made.
![vim-airline](https://cloud.githubusercontent.com/assets/5629946/14846000/14dbdc3c-0c94-11e6-91a6-212da1d67ef2.png)

Here is the screenshot, it's all the same no changes. It stay all same.
![vim-statusline](https://cloud.githubusercontent.com/assets/5629946/14845950/d9409a50-0c93-11e6-8d0a-c0ba31718b82.png)

**Comment by HendrikPetertje** [comment] 2016-05-03 11:13
hey @sarbazx,
This is caused by an issue that started some time ago.
pull requests have been sitting in this repo to fix this for some time now. I'm guessing the Astrails guys abandoned this project.

https://github.com/astrails/dotvim/pull/55 is the pull request that fixes this issue and explains the problem too.

adding this to your `~/.vimrc.bundles` should fix the issue until someone picks up this project again:

```
NeoBundle 'jdkanani/vim-material-theme'
```

**Comment by vitaly** [comment] 2016-06-25 21:53
PR #55  was merged. that beings said, I haven't updated dotvim repo for a while since I worked on dotvim2 ;). see https://github.com/vitaly/dotvim2
While its not yet finished, its already usable, and much more fast and modular. And it upgrades some outdated components too. Come beta-test guys ;)

**Closed by vitaly** 2016-06-25 21:53 UTC
